backend:
  name: github
  repo: carloscuxin/markdown-editor
  branch: main
  client_id: Ov23liUhDgzOsbFwCXsW

media_folder: "assets/uploads" # Carpeta donde se guardarán las imágenes y archivos adjuntos
public_folder: "/assets/uploads"

collections:
  - name: "wiki"
    label: "Páginas de la Wiki"
    folder: "docs" # Carpeta raíz en tu repo donde se guardarán los archivos .md creados
    create: true # Permite a los usuarios crear páginas nuevas
    slug: "{{slug}}"
    fields:
      - { label: "Título de la página", name: "title", widget: "string" }
      - { label: "Fecha de creación", name: "date", widget: "datetime" }
      - { label: "Contenido de los procesos", name: "body", widget: "markdown" } # Este activa el editor visual tipo Word
